# What src/shell.lua promises. GENERATED BY NOBODY -- written by hand, and run.
#
# This file is the half of spec/shell.md that must be true. The .md carries the argument:
# why it is `shell` and never `bash`, why determinism rather than isolation is the point,
# why a here-document is refused. An argument cannot be executed and does not belong here.
# A promise can be, and does not belong there.
#
# A scenario that FAILS means the spec says something false, which is a bug.
# A scenario that is UNDEFINED means the spec is ahead of the code, which is a to-do.
# Those are different, and the runner already tells them apart.

Feature: shell -- a shell, in Lua, over a filesystem in Lua

  Background:
    Given the file "README.md" contains:
      """
      # a workspace
      it is small
      and it is here
      """
    And the file "src/turn.lua" contains:
      """
      local turn = {}
      return turn
      """
    And the file "src/spec.lua" contains:
      """
      local spec = {}
      return spec
      """

  # ------------------------------------------------------------------ the commands

  Scenario: a listing is sorted, and a file names itself
    When the declaration is loaded
    Then running "ls" answers 0 and:
      """
      README.md
      src
      """
    And running "ls src" answers 0 and:
      """
      spec.lua
      turn.lua
      """
    And running "ls README.md" answers 0 and:
      """
      README.md
      """

  Scenario: reading, counting and slicing
    When the declaration is loaded
    Then running "cat src/spec.lua" answers 0 and:
      """
      local spec = {}
      return spec
      """
    And running "wc -l README.md" answers 0 and:
      """
      3 README.md
      """
    And running "head -n 1 README.md" answers 0 and:
      """
      # a workspace
      """
    And running "tail -n 1 README.md" answers 0 and:
      """
      and it is here
      """

  Scenario: grep is a fixed string, and its exit code is its answer
    When the declaration is loaded
    Then running "grep small README.md" answers 0 and:
      """
      it is small
      """
    And running "grep -n small README.md" answers 0 and:
      """
      2:it is small
      """
    And running "grep nothing README.md" answers 1 and:
      """
      """
    And running "grep %w README.md" answers 1 and:
      """
      """

  Scenario: a walk always names the file, even when it found one
    When the declaration is loaded
    Then running "grep -r 'local spec' src" answers 0 and:
      """
      src/spec.lua:local spec = {}
      """

  Scenario: find globs, and a star does not cross a slash
    When the declaration is loaded
    Then running "find src -name '*.lua'" answers 0 and:
      """
      src/spec.lua
      src/turn.lua
      """
    And running "find . -name 'src*'" answers 0 and:
      """
      """

  Scenario: the commands that answer nothing still answer
    When the declaration is loaded
    Then running "true" answers 0 and:
      """
      """
    And running "false" answers 1 and:
      """
      """
    And running "pwd" answers 0 and:
      """
      /
      """

  # ---------------------------------------------------------------------- the flags

  Scenario: an unknown flag is an error, and is never ignored
    When the declaration is loaded
    Then running "ls -z" answers 2 and:
      """
      """
    And running "rm -q src" answers 2 and:
      """
      """

  Scenario: a flag that is accepted either does its job or is one of the three no-ops
    When the declaration is loaded
    Then running "sort -r README.md" answers 0 and:
      """
      it is small
      and it is here
      # a workspace
      """
    And running "grep -i SMALL README.md" answers 0 and:
      """
      it is small
      """
    And running "grep -v is README.md" answers 0 and:
      """
      # a workspace
      """
    And running "ls -a src" answers 0 and:
      """
      spec.lua
      turn.lua
      """

  Scenario: cp copies a tree with -r and refuses one without
    When the declaration is loaded
    Then running "cp src copy" answers 1 and:
      """
      """
    And running "cp -r src copy" leaves "copy/turn.lua":
      """
      local turn = {}
      return turn
      """

  # ----------------------------------------------------------------------- the joins

  Scenario: the connectors join, and && skips the rest of its chain
    When the declaration is loaded
    Then running "echo one && echo two" answers 0 and:
      """
      one
      two
      """
    And running "cat nope.txt || echo fallback" answers 0 and:
      """
      fallback
      """
    And running "cat nope.txt && echo a && echo b" answers 1 and:
      """
      """

  Scenario: a pipeline's exit code is the last command's
    When the declaration is loaded
    Then running "cat README.md | grep is | wc -l" answers 0 and:
      """
      2
      """

  Scenario: a redirection truncates, appends and feeds
    When the declaration is loaded
    Then running "echo hello > greeting.txt" leaves "greeting.txt":
      """
      hello
      """
    And running "echo one > g.txt; echo two >> g.txt" leaves "g.txt":
      """
      one
      two
      """
    And running "wc -l < README.md" answers 0 and:
      """
      3
      """

  Scenario: cd lasts for the line, and not past it
    When the declaration is loaded
    Then running "cd src && ls" answers 0 and:
      """
      spec.lua
      turn.lua
      """
    And running "cd src; pwd" answers 0 and:
      """
      /src
      """

  # ------------------------------------------------------------- what it must not do

  Scenario: nothing climbs out of the workspace, through any command
    When the declaration is loaded
    Then no command reaches outside the workspace:
      | line                       |
      | cat ../../etc/passwd       |
      | ls ../..                   |
      | echo x > ../escape.txt     |
      | cp README.md ../escape.md  |
      | rm ../../thing             |
      | find .. -name '*'          |
      | grep x ../../etc/passwd    |
      | cd ..                      |

  Scenario: an unknown command is exit 127, and a here-document is refused
    When the declaration is loaded
    Then running "frobnicate --hard" answers 127 and:
      """
      """
    And running "cat <<EOF" answers 2 and:
      """
      """

  Scenario: the same script twice over the same filesystem is byte-identical
    When the declaration is loaded
    Then running "mkdir -p build; cat README.md > build/copy.md; grep -rn is .; ls -R ." twice is the same

  Scenario: it touches nothing
    When the declaration is loaded
    Then the module "src/shell.lua" names no io
    And the module "src/shell.lua" names no os
    And the module "src/shell.lua" names no popen

  # ------------------------------------------------------------------- the embed door

  Scenario: a whole agent runs with a live shell and no scripted command at all
    Given the shell really runs
    And the file "notes/a.md" contains:
      """
      one
      """
    And the human approves shell
    And the model calls shell with { "command": "cat notes/a.md > notes/b.md" }
    And the model answers "copied"
    When the agent is asked "copy the note"
    Then it calls shell
    And it stops with answered
    And the file "notes/b.md" holds:
      """
      one
      """
